### ISSUE TITLE
Extension breaks installation

### ISSUE THREAD

**Issue by millemedia** [peterbenke/pb_rel_nofollow#1]
Hi Peter,

when I install your plugin, I get the following error:
PHP Warning: simplexml_load_string(): Entity: line 1: parser error : EntityRef: expecting ';' in ../typo3conf/ext/pb_rel_nofollow/Classes/User/FrontendHook.php line 108 
Plattform: TYPO3 8.7.19 with php 7.0

Best regards 
Andreas

**Comment by peterbenke** [comment]
Hi Andreas,

maybe you have an invalid html?
Please post your source code of your html page.

Cheers
Peter

**Comment by millemedia** [comment]
Hi Peter,

attached is the souce code of the page. 
[games.focus.de.txt](https://github.com/peterbenke/pb_rel_nofollow/files/2391528/games.focus.de.txt)

Best regards

Andreas

**Comment by peterbenke** [comment]
Hi Andreas,

sorry, but this code is compressed...
Please give me a readable source code.
Ideal would be a list of all a-tags.

Cheers
Peter

**Comment by millemedia** [comment]
Hi Peter,

just wrote a script that extracts the links.
Here is the result:
[games.focus.de.txt](https://github.com/peterbenke/pb_rel_nofollow/files/2393018/games.focus.de.txt)

All the best

Andreas

**Comment by peterbenke** [comment]
Hi Andreas,

uuups, so many links.

Maybe you could create a html content only with these links.
You could do this with HTML-contentelement inside TYPO3 and paste your links there.
Then remove the links piece by piece to finally get the link(s), where the extension failes.

Cheers
Peter

**Comment by millemedia** [comment]
Hi Peter,

I identified the wrong link:

`<a href="https://www.focus.de/ajax/login/community_login?ref=https://www.focus.de/channelizer/&use_ssl=true" style="display:none;" rel="nofollow" title="Login" class="fancyboxctfreg ps-login">Login</a>`
and
`<a href="https://www.focus.de/ajax/login/community_login?ref=https://www.focus.de/channelizer/&use_ssl=true" rel="nofollow" title="Login" class="sticky-ps-login fancyboxctfreg">
    <svg class="svg-icon grey-profil"><use xlink:href="https://www.focus.de/pics/icons/menu_icons.svg#ic_profil"/></svg>
</a>`

Whats wrong with that link? I removed rel="nofollow" but that didn't make any change.

Best regards

Andreas

**Comment by peterbenke** [comment]
Hi Andreas,

thank you for the links.
I tested these links on my testserver (TYPO3 8.7.18 + php 7.0/7.1) and everything workes fine.
Then I saw, that I had to update TYPO3 to 8.7.19, I did it and everything works fine...

Sorry, I don't know where the problem is. Maybe you can test some things inside the extension code, maybe you find the issue...?

Simplexml is installed properly?
At this moment, I see, it is not documented, that simplexml is needed.

Cheers
Peter

**Comment by millemedia** [comment]
Hi Peter,

finally I find the error. Both links contains an unescaped "&". When I change that in the FLUIDTEMPLATE to &amp;, everything works fine. 

Is it possible for you to implement a function that checks for unescaped  &?

Best regards

Andreas

**Comment by peterbenke** [comment]
Hi Andreas,

sorry, but i do not have any problems with these links...

Cheers
Peter
